set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[0]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[1]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[22]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[26]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[28]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[9]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TxData[2]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TxData[7]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[2]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[10]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[25]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[26]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[5]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[19]}]
set_property MARK_DEBUG true [get_nets {UART_TX/St[1]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[2]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[3]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TxData[5]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[3]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[8]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[11]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[27]}]
set_property MARK_DEBUG true [get_nets UART_TX/TxRdy]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[30]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[2]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[7]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[15]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[18]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[20]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[5]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[12]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[14]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[14]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[30]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[6]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TxData[0]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TxData[6]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[7]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[16]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[17]}]
set_property MARK_DEBUG true [get_nets UART_TX/Start]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[4]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[9]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[11]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[16]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[31]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[0]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[4]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[13]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[19]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[24]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[31]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[29]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[10]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[21]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[25]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[27]}]
set_property MARK_DEBUG true [get_nets {UART_TX/St[0]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[1]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[5]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[4]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[1]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[15]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[20]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[28]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[3]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[12]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[29]}]
set_property MARK_DEBUG true [get_nets {UART_TX/St[2]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[8]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TxData[1]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[0]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[18]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[22]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[23]}]
set_property MARK_DEBUG true [get_nets UART_TX/Tx]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[13]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[6]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[8]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[17]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[23]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntRate[24]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TSR[7]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TxData[3]}]
set_property MARK_DEBUG true [get_nets {UART_TX/TxData[4]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[6]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[9]}]
set_property MARK_DEBUG true [get_nets {UART_TX/CntBit[21]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list Clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 10 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {UART_TX/TSR[0]} {UART_TX/TSR[1]} {UART_TX/TSR[2]} {UART_TX/TSR[3]} {UART_TX/TSR[4]} {UART_TX/TSR[5]} {UART_TX/TSR[6]} {UART_TX/TSR[7]} {UART_TX/TSR[8]} {UART_TX/TSR[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {UART_TX/TxData[0]} {UART_TX/TxData[1]} {UART_TX/TxData[2]} {UART_TX/TxData[3]} {UART_TX/TxData[4]} {UART_TX/TxData[5]} {UART_TX/TxData[6]} {UART_TX/TxData[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {UART_TX/St[0]} {UART_TX/St[1]} {UART_TX/St[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {UART_TX/CntRate[0]} {UART_TX/CntRate[1]} {UART_TX/CntRate[2]} {UART_TX/CntRate[3]} {UART_TX/CntRate[4]} {UART_TX/CntRate[5]} {UART_TX/CntRate[6]} {UART_TX/CntRate[7]} {UART_TX/CntRate[8]} {UART_TX/CntRate[9]} {UART_TX/CntRate[10]} {UART_TX/CntRate[11]} {UART_TX/CntRate[12]} {UART_TX/CntRate[13]} {UART_TX/CntRate[14]} {UART_TX/CntRate[15]} {UART_TX/CntRate[16]} {UART_TX/CntRate[17]} {UART_TX/CntRate[18]} {UART_TX/CntRate[19]} {UART_TX/CntRate[20]} {UART_TX/CntRate[21]} {UART_TX/CntRate[22]} {UART_TX/CntRate[23]} {UART_TX/CntRate[24]} {UART_TX/CntRate[25]} {UART_TX/CntRate[26]} {UART_TX/CntRate[27]} {UART_TX/CntRate[28]} {UART_TX/CntRate[29]} {UART_TX/CntRate[30]} {UART_TX/CntRate[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {UART_TX/CntBit[0]} {UART_TX/CntBit[1]} {UART_TX/CntBit[2]} {UART_TX/CntBit[3]} {UART_TX/CntBit[4]} {UART_TX/CntBit[5]} {UART_TX/CntBit[6]} {UART_TX/CntBit[7]} {UART_TX/CntBit[8]} {UART_TX/CntBit[9]} {UART_TX/CntBit[10]} {UART_TX/CntBit[11]} {UART_TX/CntBit[12]} {UART_TX/CntBit[13]} {UART_TX/CntBit[14]} {UART_TX/CntBit[15]} {UART_TX/CntBit[16]} {UART_TX/CntBit[17]} {UART_TX/CntBit[18]} {UART_TX/CntBit[19]} {UART_TX/CntBit[20]} {UART_TX/CntBit[21]} {UART_TX/CntBit[22]} {UART_TX/CntBit[23]} {UART_TX/CntBit[24]} {UART_TX/CntBit[25]} {UART_TX/CntBit[26]} {UART_TX/CntBit[27]} {UART_TX/CntBit[28]} {UART_TX/CntBit[29]} {UART_TX/CntBit[30]} {UART_TX/CntBit[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list UART_TX/Start]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list UART_TX/Tx]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list UART_TX/TxRdy]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets Clk_IBUF_BUFG]
